### ISSUE TITLE
Cannot create branch using gitflow action

### ISSUE THREAD

**Issue by karneaud** [percosys/git-controlhub#4]
after running `git flow init` and setting up the repo I tried to create a branch via the GitFlow action and got the following

> git status --porcelain --untracked-files=all
> git hf feature start responsive
> git: 'hf' is not a git command. See 'git --help'.

**Comment by percosys** [comment]
This is a fork of  [git-control](https://atom.io/packages/git-control) that supports [hubflow](https://datasift.github.io/gitflow/) an alternative to git flow. In order to use it you must first install [hubflow](https://datasift.github.io/gitflow/) If you are looking for git flow use [git-control](https://atom.io/packages/git-control)
